name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build with Maven
        run: |-
          mvn clean package
      - name: Push to the repo
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c release
          git add -f target/
          git commit -am "[bot]"
          git push -f origin release
          git checkout -
